<?php declare(strict_types=1);

namespace Magento\Quote\Api\Data;

/**
 * Stub for the generated CartItemExtensionInterface used in unit tests.
 *
 * In a full Magento installation, this interface is generated by the code
 * generation system based on extension_attributes.xml declarations.
 */
interface CartItemExtensionInterface extends \Magento\Framework\Api\ExtensionAttributesInterface
{
    /**
     * @return \Magento\SalesRule\Api\Data\RuleDiscountInterface[]|null
     */
    public function getDiscounts(): ?array;

    /**
     * @param \Magento\SalesRule\Api\Data\RuleDiscountInterface[]|null $discounts
     * @return $this
     */
    public function setDiscounts(?array $discounts);
}
